spring.application.name=ecommerce-backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Keshav@12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_TU1wmyCS0s01Fo}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:bthxtLU6zVvljAkIn95L7XSw}

server.port=${PORT:8081}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:oqmadwpj}
cloudinary.api-key=${CLOUDINARY_API_KEY:311644574419542}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:qXChiXs65JQHyNA-s6Utx0DEFz8}